const TILE = {
    COTTAGE: 0,
    VILLAGE: 1
}

const OWNER = {
    PLAYER: 1,
    ENEMY: 2
}

const ELEMENT_TYPE = {
    VILLAGE: 'VILLAGE',
    COTTAGE: 'COTTAGE',
    TROOPS: 'TROOPS',
    LINE: 'LINE'
}

const LINE_ATTACK_ID = 'LINE_ATTACK_ID'

const LINE_STATUS = {
    CORRECT: 'CORRECT',
    INCORRECT: 'INCORRECT'
}

const RECRUITMENT_POWER_UI_ELEMENT = 'recruitmentPower'
const TROOPS_UNITS_UI_ELEMENT = 'troopsUnits'

module.exports = {
    TILE,
    OWNER,
    ELEMENT_TYPE,
    LINE_ATTACK_ID,
    LINE_STATUS,
    RECRUITMENT_POWER_UI_ELEMENT,
    TROOPS_UNITS_UI_ELEMENT
}
