const LINE_ATTACK_ID = 'LINE_ATTACK_ID'

const LINE_STATUS = {
    CORRECT: 'CORRECT',
    INCORRECT: 'INCORRECT'
}

const RECRUITMENT_POWER_UI_ELEMENT = 'recruitmentPower'
const TROOPS_UNITS_UI_ELEMENT = 'troopsUnits'

const UI = {
    VILLAGE_DIV_HEIGHT: 150,
    COTTAGE_DIV_HEIGHT: 80,
    TROOPS_DIV_HEIGHT: 50,
    VILLAGE_PROGRESSBAR_SIZE: 100,
    COTTAGE_PROGRESSBAR_SIZE: 75,
    VILLAGE_PROGRESSBAR_STROKE: 10,
    COTTAGE_PROGRESSBAR_STROKE: 7
}

module.exports = {
    LINE_ATTACK_ID,
    LINE_STATUS,
    RECRUITMENT_POWER_UI_ELEMENT,
    TROOPS_UNITS_UI_ELEMENT,
    UI
}
