const LINE_ATTACK_ID = 'LINE_ATTACK_ID'

const LINE_STATUS = {
    CORRECT: 'CORRECT',
    INCORRECT: 'INCORRECT'
}

const RECRUITMENT_POWER_UI_ELEMENT = 'recruitmentPower'
const TROOPS_UNITS_UI_ELEMENT = 'troopsUnits'

module.exports = {
    LINE_ATTACK_ID,
    LINE_STATUS,
    RECRUITMENT_POWER_UI_ELEMENT,
    TROOPS_UNITS_UI_ELEMENT
}
